### ISSUE TITLE
PDF 版本每页顶部都有一部分被遮挡

### ISSUE THREAD

**Issue by saihaze** [FreeBSD-Ask/FreeBSD-Ask#115]
![截图 2023-07-31 17-15-17](https://github.com/FreeBSD-Ask/FreeBSD-Ask/assets/88817189/8ebf5a54-e82a-4700-b097-629fbd334c6a)
如题。另外，页眉和页脚似乎也可以去掉。

**Comment by ykla** [comment]
https://github.com/safreya/tobook 用于导出跑路的pdf，打印的话比gitbook导出的应该要好点。该脚本运行于 FreeBSD。

先安装需要的东西：

```
# pkg install git graphicsmagick
```

如需设置 git 代理请按跑路教程提前设置以免无法拉取项目。具体使用方法见 README.
