### ISSUE TITLE
关于i3wm系桌面安装

### ISSUE THREAD

**Issue by isNijikawa** [FreeBSD-Ask/FreeBSD-Ask#25]
互联网上可以找到一些博客与帖子讨论i3使用的, [从入门到跑路](https://book.freebsdcn.org/) 中未提及, issues 没有人提及, discussions 中也未有提及.

若真的没有i3wm系桌面安装的内容, 我想攥写一篇教程并提交, 根据wiki所述 "如果您是第一次参与本项目，请先将自己加入[贡献者名单](https://github.com/FreeBSD-Ask/FreeBSD-Ask/blob/main/di-yi-zhang-zou-jin-freebsd/di-jiu-jie-can-kao-zi-liao-yu-gong-xian-zhe-ming-dan.md)。" 我需要提起新的issues和pull request将自己加入列表么? 还是可以同攥写好的i3教程一并提交pr?

**Comment by ykla** [comment]
如有可能，请加群沟通。QQ 群905149943，加群后说明来意。

如有不便，无法加群。可以直接回复你的教程在下方。因为种种原因我暂时不能创建目录，因此合并到主分支需要约15天，合并后我会创建对应目录和填写贡献者名单。

**Comment by isNijikawa** [comment]
# 安装 i3wm

本篇写给诸位希望在 FreeBSD 上使用 i3wm 的用户们.

[i3 使用手册](https://www.freebsd.org/cgi/man.cgi?query=i3&apropos=0&sektion=1&manpath=freebsd-ports&format=html)

## 准备在前

1. 安装显卡驱动, 相关教程请移步至[第二章第九节](../di-er-zhang-an-zhuang-freebsd/di-jiu-jie-wu-li-ji-xia-xian-ka-de-pei-zhi)

2. 更新系统

    ```sh
    pkg update
    pkg upgrade
    ```

3. 安装xorg

    ```sh
    pkg install xorg
    ```

## 安装 i3wm 与必要的配置

1. 安装 i3wm

    ```sh
    pkg install -y i3
    ```

2. 安装完成后, 请在用户主目录 /usr/local/bin/i3 下创建.xinitrc 文件以便使用 startx 命令启动 i3wm:

    ```sh
    echo "/usr/local/bin/i3" >> /usr/home/你的用户名/.xinitrc
    chown 你的用户名 /usr/home/你的用户名/.xinitrc
    ```

3. 重启计算机

    ```sh
    reboot
    ```

4. 重启完成后, 在tty界面登录用户, 并使用 startx 命令启动 i3wm.

    ```sh
    startx
    ```

5. 若一切顺利, 你已经可以看到一个 i3 界面了

    ![i3wmpreview](https://raw.githubusercontent.com/isNijikawa/isNijikawa/main/asset/i3wm_preview.png)

## 参考

<http://bottlenix.wikidot.com/installing-i3wm>
<https://unixsheikh.com/tutorials/how-to-setup-freebsd-with-a-riced-desktop-part-3-i3.html#xterm>
<https://forums.freebsd.org/threads/how-to-install-i3.62305/>
<https://www.freebsd.org/cgi/man.cgi?query=i3&apropos=0&sektion=1&manpath=freebsd-ports&format=html>

**Comment by ykla** [comment]
需要等待几天。我还没有收到电脑。

**Comment by ykla** [comment]
已解决。
