### ISSUE TITLE
用英文作为文件名是否更合适

### ISSUE THREAD

**Issue by njlyf2011** [FreeBSD-Ask/FreeBSD-Ask#35]

**Comment by ykla** [comment]
点击 <https://github.com/FreeBSD-Ask/FreeBSD-Ask/blob/main/SUMMARY.md> 即可。

为了方便考虑将章节名改为 chapter 1/2/3 子章节名改为 1.1/1.2/1.3。

**Comment by ykla** [comment]
Done.
