### ISSUE TITLE
建议：

### ISSUE THREAD

**Issue by daniel-zou** [FreeBSD-Ask/FreeBSD-Ask#40]
1.章节名称可不可以用英文，或者缩写。比如，第一章：拼音会写做di-yi-zhang ,英文可以写作chp1。我看跑路教程有英文版，为啥不统一章节名呢，拼音看着太乱了。
2.导出的PDF 有很多排版错乱，宽度过长的表格被裁切，跨页的文字显示不全。以前还有epub版本，这东西现在用平板看的比较多吧。如果精力有限，都可以不提供PDF版本。
3.传播BSD知识很好，也不要把别的系统批的体无完肤。Linux确实很乱，但也没你说的那么不堪。Ubuntu、Fedora、Suse、Arch也都试用过，最终选择了Manjaro，几乎开箱即用，滚动更新，完全满足工作、娱乐，也挺好。

**Comment by ykla** [comment]
1.章节名称必须与标题的拼音/标题本身（若非中文）对应。否则会造成许多困难。仅仅把标题改成 1、2、3 并没有什么好处（我没看出来？）。如果要编辑直接点击 `https://github.com/FreeBSD-Ask/FreeBSD-Ask/blob/main/SUMMARY.md` 即可。实际上如果一个人对项目有修改看法的话，他不应该不了解这个项目的结构。而且部署网站的左下角 `编辑` 也可以直接将用户带到对应的页面。
2.请提供代码或参与改进，项目地址：[condorhero/vuepress-plugin-export-pdf-v2](https://github.com/condorheroblog/vitepress-export-pdf) 。
3.请用事实说话，哪里存在问题，而非模棱两可。
